spring.application.name=search-engine
server.port=9090
server.servlet.context-path=/hotel-search-service


spring.datasource.url=jdbc:mysql://localhost:3308/travelmarket
spring.datasource.username=root
spring.datasource.password=
spring.datasource.database=travelmarket
spring.jpa.hibernate.ddl-auto=update