spring.application.name=search-engine
server.port=9090
server.servlet.context-path=/hotel-search-service


spring.datasource.url=jdbc:mysql://54.151.179.61/travelmarket
spring.datasource.username=travelmarket
spring.datasource.password=kLm63RGj2TiyNtha
spring.datasource.database=travelmarket
spring.jpa.hibernate.ddl-auto=update
