spring.application.name=search-engine
server.port=9090
server.servlet.context-path=/hotel-search-service


spring.datasource.url=jdbc:mysql://127.0.0.1/travelmarket
spring.datasource.username=root
spring.datasource.password=Malan@201
spring.datasource.database=travelmarket
spring.jpa.hibernate.ddl-auto=update



